### ISSUE TITLE
Feature: adding new agent to specific agency

### ISSUE THREAD

**Issue by kwe712** [RWTH-ACS/clonemapy#5] opened 2022-01-21 16:29 UTC
Currently the AMS assigns a new agent to the first agency it finds that has space left, or creates a new agency if there is none. 

The idea is to give the AMS a preferred `AgencyID` when registering a new agent, so that the AMS will add the agent to that specific agency if possible.

The current workflows for adding new agents in clonemapy is as follows (writing this down half for clarity and half so @s-daehling can correct me if i'm wrong):
1. Clonemapy: `update_or_create_agent()` is called in `clonemapy/ams.py`
2. Clonemapy: Calls `new_agent()`, which posts specs for new agent(s) to `"http://"+host+"/api/clonemap/mas/"+str(masid)+"/agents"`
3. Clonemap: Handler for this (as defined in `clonemap/pkg/ams/handler.go`) unmarshals content and calls `ams.createAgents()`
4. Clonemap: `ams.createAgents()` adds new agent(s) and either posts them to an existing agency or creates a new one if no space is left

The posting of the agents to the clonemap AMS (step 2) gives the needed information in the format of the `ImageGroupSpec` schema. This contains the `ImageGroupConfig` as well as the `AgentSpec` struct, which does not contain a field for the `AgencyID`.

So the question is how to communicate an `AgencyID` along this path while sticking to the existing data models as much as possible.
If we were to add e.g. a function `post_agents_to_agency()` to `clonemapy/ams.py`,  which takes the preferred `AgencyID` as an additional parameter, we would need to post using a data model that contains that ID in addition to `AgentSpec` and `ImageGroupConfig`, in order for a (new) handler within the ams to be able to parse it.

I'm posting this issue here because the question came up with @FWuellhorst regarding clonemapy first. To implement this though, changes to clonemap itself (adding a new handler and updating `createAgents()` with e.g. an optional parameter for the `AgencyID`) would also be necessary.

@s-daehling what do you think about this? Do you think there is a least-invasive way to do this?

**Comment by s-daehling** [comment] 2022-01-23 19:45
You described the current workflow for agent creation correctly :).

I am actually somewhat hesitant to implement the feature you are asking for. There are two reasons:
1. cloneMAP was created to be executed on k8s. One important requirement was to hide the complexity of k8s to the user. The user should focus on developing agent behaviors and specifying the MAS. Mapping this to k8s resources and composing single containers should be done by cloneMAP. If we allow the user to schedule agents to specific agencies, we bring back a certain amount of complexity. In a more provocative way I could say: If the user starts composing individual containers (agencies) by themselves, what do we need cloneMAP for?
2. The concrete agency ID is determined at runtime. So is the imagegroup ID. If the same MAS is executed multiple times, but the order in which agents are started is altered or the number of agents per agency is changed, the agency ID that was used in a previous execution cannot be used again. This could lead to unexpected behavior.

Could you give me a little bit more background on your usecase? Why would this feature be important? Do you want to ensure that certain agents always end up in the same agency? if yes, why?
Maybe we can achieve the desired behavior in a different way. We could add a feature of scheduling agents based on a tagging methodology. The `AgentSpec` struct could be extended by a `Tag` field. Here the user could add a list of tags (strings). Subsequently the AMS tries to schedule agents with the same tags into the same agencies.
Would that help you?

**Comment by FWuellhorst** [comment] 2022-01-25 07:40
@s-daehling : Thanks for the explanations. I totally agree. My use-case is the following: A central agents uses services (agents) to fulfill it's main goal. If an error occurs in one sub-agent, i.e. due to a rare error in a simulation, the central agent (coordinator) should be able to detect that this agent is not working anymore and act on it. 
Either notify the user to look at the error stack or by just restarting the service/agent, hoping that the error was just "bad luck".

The only issue I see right now is, that empty agencies are not used anymore. If this is now fixed, I don't need any further fixes. Thanks for the quick help!

Regarding the AgentSpec: Same as for resetting the MAS. Could be a feature in future versions. I don't need it right now.
If I want multiple AgentLib agents in one agency, I could also create a LocalMAS in on agent and deploy this agent in cloneMAP (e.g. to only allow local communication or some similar use-case).

**Comment by s-daehling** [comment] 2022-01-30 11:41
Yes, reusing agencies is now implemented.
@FWuellhorst @kwe712 
Since the feature you asked for is not required anymore, can I close this issue?

**Comment by FWuellhorst** [comment] 2022-01-31 11:03
Yes, thanks for the quick fix!

**Closed as completed** 2022-02-07 10:34 UTC
Labels: enhancement
